title: Niemi Bros Entertainment # your name (or website title) here
logo: "/images/Logo.png?raw=true" # logo/image of site
description: > # your text below (remove <br> elements if you don't need line breaks)
   
  <br>We are a team of 2 brothers who just happen to make games. Our focus is to create games inspired by ones we have enjoyed playing since our childhood. 

We are currently working on a medieval-fantasy RPG with local multi-player titled, The Arcane Relics™ (TAR), along with smaller side projects.

TAR is something we’ve been experimenting with since 2009 and developing since late 2014.<br>
  
  #<a href="HTTPS://WWW.LINKEDIN.COM/pub/ANDREW-NIEMI/55/545/B07/">FB</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
